### PR TITLE
SearchBar Position Fix

### PR DESCRIPTION
**Pull request by Dhanush834**
## Description
Margin Fix of SearchBar in Navbar of Homepage 

## Related Issue

Issue #900 

## How Has This Been Tested?

This Code is tested and verified by running in Local Host 

## Screenshots or GIF (In case of UI changes):

Without Margin UI :-

image

After Changing and adding margin :-

image

### CODE REVIEW

**Comment by Dhanush834** [comment]
@Sarfraz-droid @shivareddy6 @ABHISHEK-PANDEY2 Please review it

**Comment by shivareddy6** [comment]
Why are there changes related to notifications in your pr. Can you please clean the unnecessary changes.

**Comment by Dhanush834** [comment]
> Why are there changes related to notifications in your pr? Can you please clean the unnecessary changes.

I was working on Notification Issue unknowingly i pushed it that is the reason ... Now i have cleared it please Check it now

**Comment by shivareddy6** [comment]
can you resolve the conflicts and we can proceed with your pr

**Pull request closed without merging**
