### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by kushalShukla-web**
## Description

1. give some margin to top of card element 
2. make page responsive using align:center attribute
3. give some shadow background
## Motivation and Context

to make responsive web 
## Screenshots or GIF (In case of UI changes):
Screenshot (133)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
@charithccmc  can u pls check it once ..

**Comment by kushalShukla-web** [comment]
@charithccmc is this looks good . Or do i need to update it's UI

**Comment by Sarfraz-droid** [comment]
@kushalShukla-web can you link the related issue?

**Comment by kushalShukla-web** [comment]
I didn't find issue regarding this . I guess it's closed by me by mistake. Can I recreates this issue now .

**Comment by Sarfraz-droid** [comment]
in that case, please rename the PR title according to the related issue and add a new GIF showing the changes

**Comment by kushalShukla-web** [comment]
this pr resolve issue #465

**Comment by Sarfraz-droid** [comment]
This pr has merge conflicts.
*in that case, please rename the PR title according to the related issue and add a new GIF showing the changes as well*

**Comment by Sarfraz-droid** [comment]
Closing this pr due to inactivity

**Pull request closed without merging**
