### PR TITLE
Validate mail 

### PR DESCRIPTION
**Pull request by kushalShukla-web**
make some changes in  "SEND ME THE LINK"  so that when user type right email (any like yahoo, or any other ) formate , then only he has access to the button other wise it will disabled . 
## How Has This Been Tested?

go to forgottpassword page then as per repo , you can send email even if email is written in wrong formate .
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
@ABHISHEK-PANDEY2 bro pls check this pr .

**Comment by kushalShukla-web** [comment]
actually i created another branch for this bug . when i setup my project in linux i cant find my old branches thats why .

**Comment by Sarfraz-droid** [comment]
@kushalShukla-web The changes are failing a few cypress tests. can you look over to it?

**Comment by kushalShukla-web** [comment]
ya sure

**Comment by kushalShukla-web** [comment]
when i search first error (cypress Tests/cypress-run(pull_request) it says this 
According to the error message, the cy.click() command failed because the button element with the data-testid="forgotPasswordButton" attribute is disabled. As a result, the test case cannot interact with the disabled button.

To address this issue, you have a couple of options:

    Enable the button: Modify your test environment or test data to ensure that the button is enabled for the "empty email" scenario. You can inspect the application code and determine the conditions under which the button becomes enabled. Update your test setup or configuration accordingly.

    Use {force: true} option: If you want to forcefully interact with the disabled button despite the error checking, you can pass the {force: true} option to the cy.click() command. However, be cautious when using this option, as it bypasses Cypress's built-in error checking mechanisms.

Here's an example of how to use {force: true} with the cy.click() command:

javascript

cy.get('button[data-testid="forgotPasswordButton"]').click({force: true});

By using one of these approaches, you should be able to overcome the issue of interacting with the disabled button and fix the failing test case.

**Comment by kushalShukla-web** [comment]
but i dont know where i have to put this command cy.get('button[data-testid="forgotPasswordButton"]').click({force: true}); as i have only pushed single file .

**Comment by kushalShukla-web** [comment]
im having trouble while going through some cypress Tests .

**Comment by kushalShukla-web** [comment]
i use  .should('be.disabled') as cy.should('be.disabled') but i think that also is not working

**Comment by Sarfraz-droid** [comment]
Hi @kushalShukla-web 
The test change was to update it to as
```
 cy.get("[data-testId=forgotPasswordButton]").should('be.disabled');
```

although I have fixed it for now.  You can see more about cypress docs at https://docs.cypress.io/api/commands/should

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by kushalShukla-web** [comment]
sounds good . and yes im going to go through the cypress document

**Review by Maahi10001 — APPROVED** [review]

**Review by shivareddy6 — APPROVED** [review]

**Pull request merged**
