### PR TITLE
Changes in databaseURL for config

### PR DESCRIPTION
**Pull request by Maahi10001**
## Description
Actually the previous url "https://${process.env.REACT_APP_FIREBASE_PROJECT_ID}.firebaseio.com" is does seems to be help in storing the user data and need to be updated to this   "https://DATABASE_NAME.REGION_NAME.firebasedatabase.app"

## Related Issue
Storage issue in site with firebase 
Database URL chnage
issue #242 

## Motivation and Context
This will fix the issue #242  where actually the problem is the firebase is not acccessable if you change the url manually with your Realtiem db think will work

## Types of changes

- fixes the issue #242 
- change the URL in config file

### CODE REVIEW

**Review by Niweera — APPROVED** [review]

**Comment by Maahi10001** [comment]
@Wathsara  @charithccmc  can you check this once

**Review by Wathsara — APPROVED** [review]

**Review by swapnalshahil — APPROVED** [review]

**Comment by shahaab** [comment]
@Niweera this pr hasn't been merged even after approval, but issue #242 for which the pr was made has been closed.

**Comment by Maahi10001** [comment]
> @Niweera this pr hasn't been merged even after approval, but issue #242 for which the pr was made has been closed.

No need of merging this i guess just close it as completed coz the changes have been made on other.

**Comment by shahaab** [comment]
> > @Niweera this pr hasn't been merged even after approval, but issue #242 for which the pr was made has been closed.
> 
> No need of merging this i guess just close it as completed coz the changes have been made on other. As the changes in database url will differ for everyone based on the region they select while creating the db in firebase so no problem.

okay thanks

**Pull request closed without merging**
