### PR TITLE
Refactor sidebar component code

### PR DESCRIPTION
**Pull request by abdullahranginwala**
## Description

https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/sidelist.js
- Refactored the code to remove auth based check.

https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/index.js
-Dynamically updated defaultMenu with useMemo().

## Related Issue

https://github.com/scorelab/Codelabz/issues/456

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Sarfraz-droid** [comment]
@abdullahranginwala can you attach a screenshot or GIF of the home page? just to make sure there are no breaking changes

**Comment by abdullahranginwala** [comment]
There seems to be some issue with my usage of useMemo(). I am still a little confused of how we will dynamically update the defaultMenu.

**Comment by Sarfraz-droid** [comment]
@abdullahranginwala the sidebar menu requires quite a few changes, so I'll add a commit related to that on this pr. thank you

**Comment by abdullahranginwala** [comment]
Alright!

**Comment by Sarfraz-droid** [comment]
Hi, @abdullahranginwala actually there are too many breaking changes, so we might have to re-write the side-list part again.
sorry for the trouble

**Comment by abdullahranginwala** [comment]
No worries. appreciate your help

**Pull request closed without merging**
