### PR TITLE
Made Icons Consistent

### PR DESCRIPTION
**Pull request by hs05june**
## Related Issue

 #542 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Sarfraz-droid** [comment]
@hs05june can you add in  a screenshot or gif to show the changes

**Comment by hs05june** [comment]
@Sarfraz-droid 

https://user-images.githubusercontent.com/103871275/208927775-d4e27f1c-d457-4edf-8b17-8b48575eb4af.mp4

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by hs05june** [comment]
@Maahi10001 @shahaab @Niweera Kindly review this PR.

**Comment by shahaab** [comment]
Good, also align the first column(Facebook and the google icon) @hs05june

**Review by Maahi10001 — APPROVED** [review]

**Pull request merged**
