### PR TITLE
Notification

### PR DESCRIPTION
**Pull request by kushalShukla-web**
## Description

changed notification card UI as per given in figma . 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
@Sarfraz-droid can you pls check this pr :). its just a small change

**Comment by Sarfraz-droid** [comment]
Hey @ABHISHEK-PANDEY2 , Can you go through it?

**Comment by ABHISHEK-PANDEY2** [comment]
Hey, @kushalShukla-web can you please attach some screenshots of the changes

**Comment by kushalShukla-web** [comment]
Screenshot from 2023-07-22 01-30-39
here change is small . as there is vertical outlined icon is present so i changed that one to horizontal according to figma . and then put style property so that it can go to top right corner of a notification card .

**Review by ABHISHEK-PANDEY2 — APPROVED** [review]

**Review by shivareddy6 — APPROVED** [review]

**Review by Maahi10001 — APPROVED** [review]

**Pull request merged**
