### PR TITLE
added input fields for organisation social media handles

### PR DESCRIPTION
**Pull request by IITvamp**
## Description
added fields for organization to update social media handles.
connected the fields with backend data

## Related Issue
#470 

## Screenshots or GIF (In case of UI changes):
image

image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Maahi10001** [comment]
I guess we already have a seperate tab for social media right? So social media input fields are required?

**Comment by IITvamp** [comment]
> I guess we already have a separate tab for social media right? Do we need social media input fields again?

That tab is used for accessing those links. But we do not have, yet, fields to enter those links at the first place. Correct me if I am wrong.

**Comment by IITvamp** [comment]
> I guess we already have a seperate tab for social media right? Do we need social media input fields again?

I understood what you are saying. Currently, we do not have the functionality to connect social media handles to our accounts. that's why what we can do is provide them a space to enter their handles manually.

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by Maahi10001** [comment]
> > I guess we already have a seperate tab for social media right? Do we need social media input fields again?
> 
> I understood what you are saying. Currently, we do not have the functionality to connect social media handles to our accounts. that's why what we can do is provide them a space to enter their handles manually.
 okay got it.

**Review by Maahi10001 — APPROVED** [review]

**Pull request merged**
