### PR TITLE
Setup Husky #854

### LINKED ISSUE #854: Setup Husky for auto formatting on pre commit
There have been multiple issues while reviewing due to issues with conflicting formats.
 
feature: add Husky for a pre-commit hook to run code formatting and linting before commits. 
reference: https://typicode.github.io/husky/

### PR DESCRIPTION
**Pull request by MuntazirHaider**
## Description

For husky setup I take following steps -:

1. Run npm install husky --save-dev and npx husky-init && npm install
2. These commands make a directory named husky in root directory. In .husky/pre-commit file replace npm test to npm run lint
npm run format
3. Modify package.json, In script add lint and format. Add husky configuration in package.json.
4. In eslintrc.cjs file replace ecmaVersion to 2017

## Related Issue

Fixes #854 

## Motivation and Context

There have been multiple issues while reviewing due to issues with conflicting formats.
Adding Husky to your project to enforce code formatting and linting before commits is a great way to maintain code quality.

## How Has This Been Tested?

For Testing husky setup Suppose we have a formatting or linting issue try to commit if Husky blocks the commit due to ESLint issues, review the ESLint output and address the reported issues in your code. Once the issues are resolved, you can attempt the commit again if Husky doesn't block the commit this time and the commit goes through, it means its working fine. If you want to commit with linting and formatting issues run git commit -m "Commit Message" --no-verify

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Sarfraz-droid — APPROVED** [review]

**Review by Sarfraz-droid — APPROVED** [review]

**Comment by Sarfraz-droid** [comment]
Great work @MuntazirHaider !

**Comment by MuntazirHaider** [comment]
Thank You @Sarfraz-droid  
 I'm eager to contribute more to open source. Could you suggest some issues I could work on? Are there any specific projects or repositories you recommend exploring?

**Review by ABHISHEK-PANDEY2 — APPROVED** [review]

**Comment by ABHISHEK-PANDEY2** [comment]
@MuntazirHaider Could you please resolve the conflicts ?

**Comment by MuntazirHaider** [comment]
> @MuntazirHaider Could you please resolve the conflicts ?

Done 👍

**Comment by shivareddy6** [comment]
@MuntazirHaider, there are still some conflicts left. Please resolve them.

**Comment by Sarfraz-droid** [comment]
@ABHISHEK-PANDEY2 @shivareddy6 Husky setup LGTM.

**Comment by Sarfraz-droid** [comment]
@shivareddy6 @Maahi10001 @ABHISHEK-PANDEY2 please review

**Review by shivareddy6 — APPROVED** [review]

**Review by ABHISHEK-PANDEY2 — APPROVED** [review]

**Pull request merged**
