### PR TITLE
1. changed readme.md file 2. deleted favicon.ico 3. deleted logo.svg

### PR DESCRIPTION
**Pull request by kushalShukla-web**
1.a small change made in readme.md file .  
2.deleted favicon.ico file
3.deleted logo.svg file (a react logo which is not necessary)
## Motivation and Context

this project contains some  unnecessary files like i mentioned above and there is typo error in readme.md file
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
hey @charithccmc  can u pls look in this pull request ..

**Comment by rijusougata13** [comment]
can't see any reasonable changes in readme file? what's the heading about @kushalShukla-web

**Comment by kushalShukla-web** [comment]
Sry for that heading @rijusougata13 . Ya actually there is typo error "fir" . I manage to overcome that error

**Comment by shahaab** [comment]
Hey @Niweera you can close this.

**Pull request closed without merging**
