### PR TITLE
Rename README.md to Merged_README.md

### PR DESCRIPTION
**Pull request by jayeshuk**
Worked on the Issue #770 (Merge Old and Current README)

## Related Issue

#770 

## Motivation and Context
It resolved the problem of referring 2 README files in Vite branch

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Sarfraz-droid** [comment]
@Maahi10001 please have a look at it!

**Review by Maahi10001 — APPROVED** [review]
LGTM

**Comment by Sarfraz-droid** [comment]
Should we? @Maahi10001 Because the current docs don't have any conflicts with the master. Its updated and might end up having confusions for the first time contributors.

**Comment by Maahi10001** [comment]
> Should we? @Maahi10001 Because the current docs don't have any conflicts with the master. Its updated and might end up having confusions for the first time contributors.

Yes this can be an issue lets follow the existing one we can later modify.

**Comment by jayeshuk** [comment]
Sure, Thanks

**Pull request closed without merging**
