### PR TITLE
Logochange

### PR DESCRIPTION
**Pull request by IITvamp**
## Description

- added 6 more names to Codelabz brand names that match with the existing brand names
- 6 names make the total brand names 13, hence whenever the user logs into the website, he will see a different name for 13 hours.
- `CoDeLaBz`, -> a string with alternative uppercase and lowercase letter
    `Codel@bz`, -> a string using '@' instead of "a"
    '${Codelabz}', -> a string using javascript functionality to show 'Codelabz' string
    `3o45l12z`,    //a-> 1, c-> 3, d-> 4, e-> 5   -> a string using numerical values replacing 'a','b','c','d' with 1,2,3,4 respectively 
    ` C for Codelabz`,   ->  a string introducing C for Codelabz i.e. changing the way we teach kids alphabets (In India C for Cat is taught to children)
    `console.log("codelabz")`  -> a string using javascript console.log function to console 'codelabz'

## Related Issue
#271 

## Motivation and Context

- In the online era, a person generally spends 11-12 hours on the screen each day so its good to show him a different name each time user logs in to keep up his enthusiasm

## How Has This Been Tested?
by logging in at different hours

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shahaab** [comment]
Personally I don't think this is a good idea to keep changing logos. but we must make a new logo for codelabz.

**Comment by IITvamp** [comment]
> I don't think this is a good idea to keep changing logos. but we must make a new logo for codelabz.

we are already using this approach of changing logos each hour for the user. in this pr I added a few more logos, to take the count of logos to 13.
though we can close this pr if we are looking for an entirely new logo for codelabz.

**Comment by shahaab** [comment]
> > I don't think this is a good idea to keep changing logos. but we must make a new logo for codelabz.
> 
> we are already using this approach of changing logos each hour for the user. in this pr I added a few more logos, to take the count of logos to 13. though we can close this pr if we are looking for an entirely new logo for codelabz.

@charithccmc @Niweera is there any specific reason why we have this feature?

**Comment by Niweera** [comment]
> > > I don't think this is a good idea to keep changing logos. but we must make a new logo for codelabz.
> > 
> > 
> > we are already using this approach of changing logos each hour for the user. in this pr I added a few more logos, to take the count of logos to 13. though we can close this pr if we are looking for an entirely new logo for codelabz.
> 
> @charithccmc @Niweera is there any specific reason why we have this feature?

there is no specific reason. if it is problematic we can drop it.

**Pull request closed without merging**
