### PR TITLE
Fixed the upvote and downvote being negative and unlimited voting issue

### LINKED ISSUE #995: No limitation to the upvote or downvote and no hover text in the buttons
**Describe the bug**
When we add a new Codelabz, there is a functionality of upvote and downvote. But right now, there is not limitation for an user. They can upvote or downvote n number of times.
Also, there is no hover text in the share, bookmark and comment buttons in the same.
**To Reproduce**

1. Go to 'http://localhost:5173/tutorials' and add on "add new codelabz"
2. Click on '(http://localhost:5173/)'
3. Scroll down to the codelabz and the upvote, downvote, comment bookmark and share buttons

**Expected behavior**
The upvote or downvote button should allow users to only be able to vote once, and then they can either keep that or change their vote.
The comment, bookmark and share button should show their names when hovering over it

**Screenshots**
image
**Desktop (please complete the following information):**
image

- OS: Windows
- Browser Brave
- Version- Latest

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
## Description
Worked on fixing the votes being negative and user being able to vote an unlimiited number of times

## Related Issue
Fixes #995 

## Motivation and Context

This change is required to have legitimacy. In the future when the votes are connected to the db, the user should be able to vote in real manner and see the votes throughout

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Aditya-Sakpal** [comment]
This issue was already fixed by me , in the previous pr , please check whether the issue is already been created and resolved before.

**Comment by PoulavBhowmick03** [comment]
> This issue was already fixed by me , in the previous pr , please check whether the issue is already been created and resolved before.

Yeah but were you assigned? I am not sure how it works here since I haven't spoken to the mentors but Abhishek did assign me the issue.

**Comment by PoulavBhowmick03** [comment]
@Maahi10001 @shivareddy6  Can you please look into this PR?

**Comment by Aditya-Sakpal** [comment]
> > This issue was already fixed by me , in the previous pr , please check whether the issue is already been created and resolved before.
> 
> Yeah but were you assigned? I am not sure how it works here since I haven't spoken to the mentors but Abhishek did assign me the issue.

Na na it's all good , I was just saying it would be better if we all work on different issues , since it would be more efficient from the org's perspective .

**Pull request closed without merging**
