### PR TITLE
Removed repeated Table of contents in CONTRIBUTING.md

### LINKED ISSUE #797: Repeated `Table of Contents` on Contributing.md
*Documentation*: In Contributing.md. The Table of Contents are repeated twice. 
- Table of Content from line 1.
- Table of Content from line 127

Both can be updated/removed accordingly.

### PR DESCRIPTION
**Pull request by giri-madhan**
## Description

Removed repeated Table of contents menu from `CONTRIBUTING.md` file.

## Related Issue

This fixes #797 

## Motivation and Context

This removes the Table of contents menus that are wrong.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Sarfraz-droid** [comment]
@giri-madhan There's also a section below "Run the Tests" heading. We can remove that section as well.

**Review by Sarfraz-droid — CHANGES_REQUESTED** [review]
There's also a table of content section below "Run the Tests"(line 124) heading. Please remove that section as well.

**Review by Sarfraz-droid — CHANGES_REQUESTED** [review]
There's also a table of content section below "Run the Tests"(line 124) heading. Please remove that section as well.

**Comment by giri-madhan** [comment]
Hi @Sarfraz-droid ? Could you please check once if this new commit looks okay?

**Comment by Sarfraz-droid** [comment]
I guess the CI/CD has crashed due to the recent update in firebase-tools. This will be merged after #800 gets resolved

**Review by Maahi10001 — APPROVED** [review]

**Comment by giri-madhan** [comment]
Thank you for the merge @Maahi10001

**Pull request merged**
